name: Deploy Remix App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Log in to ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build and push Docker image to ECR
      run: |
        IMAGE_TAG=latest
        IMAGE_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/remix-portfolio:$IMAGE_TAG
        docker build -t $IMAGE_URI .
        docker push $IMAGE_URI

    - name: Deploy to EC2
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > private_key && chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key ec2-user@${{ secrets.EC2_PUBLIC_IP }} << EOF
        sudo aws ecr get-login-password --region us-east-1 | sudo docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com
        sudo docker system prune --all --force --volumes
        # Identify the container running on port 3000 and stop it if it exists
        CONTAINER_ID=\$(sudo docker ps --filter "publish=3000" --format "{{.ID}}")
        if [ -n "\$CONTAINER_ID" ]; then
          echo "Stopping container running on port 3000..."
          sudo docker stop \$CONTAINER_ID
          sudo docker rm \$CONTAINER_ID
        else
          echo "No container running on port 3000."
        fi

        sudo docker system prune --all --force --volumes
        
        # Pull the new image
        sudo docker pull $IMAGE_URI
        
        # Run the new container
        sudo docker run -d --name remix-portfolio -p 3000:3000 $IMAGE_URI

        sudo docker system prune --all --force --volumes
        EOF
      env:
        IMAGE_URI: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/remix-portfolio:latest

    - name: Cleanup Old ECR Images
      run: |
        REPO_NAME=remix-portfolio
        # List images sorted by `imagePushedAt`, keeping only the two most recent ones
        aws ecr describe-images --repository-name $REPO_NAME --query 'sort_by(imageDetails,&imagePushedAt)[*].[imageDigest,imageTag]' --output json > all_images.json
        TOTAL_IMAGES=$(jq '. | length' all_images.json)
        
        if [ "$TOTAL_IMAGES" -gt 2 ]; then
          echo "Total images: $TOTAL_IMAGES"
          IMAGES_TO_DELETE=$(jq '. | .[:-2]' all_images.json)
          
          echo "Images to delete:"
          echo "$IMAGES_TO_DELETE"
          
          echo "$IMAGES_TO_DELETE" | jq -c '.[]' | while read image; do
            DIGEST=$(echo $image | jq -r '.[0]')
            echo "Deleting image with digest: $DIGEST"
            aws ecr batch-delete-image --repository-name $REPO_NAME --image-ids imageDigest=$DIGEST
          done
        else
          echo "No images to delete. Total images ($TOTAL_IMAGES) is less than or equal to 2."
        fi
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1
